eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/customers/**
        - id: order-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/orders/**