server:
  port: 8091

spring:
  application:
    name: orders-service

  datasource:
    url: jdbc:sqlserver://localhost:1465;databaseName=Northwind;trustServerCertificate=true;
    username: sa
    password: $Admin2024
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/